# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, '9.0'
inhibit_all_warnings!

target 'ShuiKu' do
  
pod 'AFNetworking'
pod 'SDWebImage', '~> 4.0'
pod 'Masonry', '~> 1.1.0'
pod 'YYKit', '~> 1.0.9'
pod 'MJExtension', '~> 3.0.13'
pod 'MJRefresh'
pod 'CYLTabBarController', '~> 1.17.4'
pod 'TZImagePickerController'
pod 'IQKeyboardManager'
pod 'YLGIFImage'
pod 'MBProgressHUD', '~> 1.0.0'

end
